version: "2"

run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unconvert
    - gosec
  settings:
    revive:
      severity: warning
    gocritic:
      enabled-checks:
        - boolExprSimplify
  exclusions:
    generated: lax
    rules:
      - path: _test\.go$
        linters:
          - gosec

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
